---
title: "Hinz_Daniel_Assignment5_R"
author: 'Submitted by Daniel Hinz (Student ID: 6302371)'
date: "25.01.2023"
output:
  html_document:
    toc: yes
  pdf_document:
    toc: yes
---

```{r setup, include = F}
options(scipen=999)
```



```{r warning=FALSE}
library(jsonlite)
library(httr)
library(rlist)
library(tidyverse)
setwd("D:/Dokumente/Studium/Master_DataScience/Assignment5")


```




```{r warning=FALSE}
key <- read.table("key.txt", header = FALSE)

response <- GET("https://app.ticketmaster.com/discovery/v2/venues",
                query = list(apikey = key[1],
                             countryCode = "DE")) %>% content()

response$page

```

```{r warning=FALSE}
# Function to query the nested dictionary which we receive from the API
querydict <- function(dict, ...) {
    
    #This function needs a dictionary and one or multiple keys. Output is the element stored behind the key or no value
    #if that element is not present
      
  # for some instances we have two keys, if that is the case, query both an get the element
  keys <- list(...)
  for (key in keys) {
    if (!is.null(dict[[key]])) {
      dict <- dict[[key]]
    } else {
  # if that particular entry is not present return no value

        return("no value")
    }
  }
  return(dict)
}

```

```{r warning=FALSE}
# Define output Dataframe with columns that we would like to extract
output_df <- data.frame(matrix(ncol = 7, nrow = 0))
colnames(output_df) <- c("name", "city", "postalCode", "address", "url", "longitude", "latitude")

venues <- response$"_embedded"$venues

# loop over all entries in venues
for (i in venues) {
  
  # initiate output list
  output_list <- list()
  
  # add input to output list
  output_list <- append(output_list, querydict(i,"name"))
  output_list <- append(output_list, querydict(i,"city","name"))
  output_list <- append(output_list, querydict(i,"postalCode"))
  output_list <- append(output_list, querydict(i,"address","line1"))
  output_list <- append(output_list, querydict(i,"url"))
  output_list <- append(output_list, querydict(i,"location","longitude"))
  output_list <- append(output_list, querydict(i,"location","latitude"))
  
  # append output list to dataframe
  output_df[nrow(output_df)+1,] <- output_list
  

}
head(output_df)

```
### Interacting with the API advanced

```{r warning=FALSE}

# Define output Dataframe with columns that we would like to extract
output_df_all <- data.frame(matrix(ncol = 7, nrow = 0))
colnames(output_df_all) <- c("name", "city", "postalCode", "address", "url", "longitude", "latitude")

# loop over all pages
for (page in 1:48){
  response <- GET("https://app.ticketmaster.com/discovery/v2/venues",
                  query = list(apikey = key[1],
                               countryCode = "DE",
                               page = page,
                               size = 100)) %>% content()
 # if the API returns an error, try to query the page again
  tryCatch({
    venues <- response$"_embedded"$venues},
    error = function(e) {page <- page-1})
  
  # iterate over all 100 elements in venues
  for (i in venues) {
    
    # initiate output list
    output_list <- list()
    
    # add values to list
    output_list <- append(output_list, querydict(i,"name"))
    output_list <- append(output_list, querydict(i,"city","name"))
    output_list <- append(output_list, querydict(i,"postalCode"))
    output_list <- append(output_list, querydict(i,"address","line1"))
    output_list <- append(output_list, querydict(i,"url"))
    output_list <- append(output_list, querydict(i,"location","longitude"))
    output_list <- append(output_list, querydict(i,"location","latitude"))
    
    # append output list to dataframe
    output_df_all[nrow(output_df_all)+1,] <- output_list
    
    
  }
}
head(output_df_all)
```

### Visualizing the extracted data

```{r}
library(ggplot2)

output_df_all <- output_df_all[!(output_df_all$longitude=="no value" | output_df_all$latitude=="no value"),]


output_df_all$longitude <- as.numeric(output_df_all$longitude)
output_df_all$latitude <- as.numeric(output_df_all$latitude)


ggplot() +
  borders("world", "Germany", colour = "black", fill = "grey90") +
  theme_void() +
  coord_quickmap() +
  geom_point(data=output_df_all, aes(longitude, latitude)) +
  labs(title = "Event locations across Germany",
       caption = "Source: ticketmaster.com") +
  theme(title = element_text(size=8, face='bold'),
        plot.caption = element_text(face = "italic"))


```

```{r}
output_df_all <- output_df_all[(output_df_all$longitude > 5.866 & output_df_all$longitude < 15.042),]
output_df_all <- output_df_all[(output_df_all$latitude > 47.270 & output_df_all$latitude < 55.059),]


ggplot() +
  borders("world", "Germany", colour = "black", fill = "grey90") +
  theme_void() +
  coord_quickmap() +
  geom_point(data=output_df_all, aes(longitude, latitude)) +
  labs(title = "Event locations across Germany",
     caption = "Source: ticketmaster.com") +
  theme(title = element_text(size=8, face='bold'),
      plot.caption = element_text(face = "italic"))


```

## Event locations in other countries

```{r}

# Lets pick Italy
# Define output Dataframe with columns that we would like to extract
output_it <- data.frame(matrix(ncol = 7, nrow = 0))
colnames(output_it) <- c("name", "city", "postalCode", "address", "url", "longitude", "latitude")

# loop over all pages

response <- GET("https://app.ticketmaster.com/discovery/v2/venues",
                query = list(apikey = key[1],
                             countryCode = "IT",
                             size = 100)) %>% content()

venues <- response$"_embedded"$venues

# iterate over all 100 elements in venues
for (i in venues) {
    
  # initiate output list
  output_list <- list()
    
  # add values to list
  output_list <- append(output_list, querydict(i,"name"))
  output_list <- append(output_list, querydict(i,"city","name"))
  output_list <- append(output_list, querydict(i,"postalCode"))
  output_list <- append(output_list, querydict(i,"address","line1"))
  output_list <- append(output_list, querydict(i,"url"))
  output_list <- append(output_list, querydict(i,"location","longitude"))
  output_list <- append(output_list, querydict(i,"location","latitude"))
    
  # append output list to dataframe
  output_it[nrow(output_it)+1,] <- output_list
    
    
}

head(output_it)
```

```{r}
# remove all na and no value rows in longitude & latitude
output_it <- output_it[!(output_it$longitude=="no value" | output_it$latitude=="no value"),]
output_it <- drop_na(output_it, any_of(c("longitude","latitude")))

# transform to numeric
output_it$longitude <- as.numeric(output_it$longitude)
output_it$latitude <- as.numeric(output_it$latitude)

# Plot Map of italy including coordinates
ggplot() +
  borders("world", "Italy", colour = "black", fill = "grey90") +
  theme_void() +
  coord_quickmap() +
  geom_point(data=output_it, aes(longitude, latitude)) +
  labs(title = "Event locations across Italy",
       caption = "Source: ticketmaster.com") +
  theme(title = element_text(size=8, face='bold'),
        plot.caption = element_text(face = "italic"))


```




```{r}

# remove outlier
output_it <- output_it[(output_it$longitude > 0 & output_it$longitude > 0),]


# plot map of Italy
ggplot() +
  borders("world", "Italy", colour = "black", fill = "grey90") +
  theme_void() +
  coord_quickmap() +
  geom_point(data=output_it, aes(longitude, latitude)) +
  labs(title = "Event locations across Italy",
     caption = "Source: ticketmaster.com") +
  theme(title = element_text(size=8, face='bold'),
      plot.caption = element_text(face = "italic"))


```